export enum FixedTestCode {
  TEST_16PF = 'TEST_16PF',
  TEST_DISC = 'TEST_DISC',
  TEST_IL = 'TEST_IL',
  TEST_CFR = 'TEST_CFR',
  TEST_IC = 'TEST_IC',
  TEST_TAC = 'TEST_TAC',
  TEST_CEAL = 'TEST_CEAL',
  TEST_BIS11 = 'TEST_BIS11',
}
